name: esus

services:
  web-api:
    build: .
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db-postgres
    
  db-postgres:
    image: postgres:14.11-alpine
    restart: always   
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
